spring.application.name=attendance-system
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/attendance_system?useSSL=false&serverTimezone=GMT%2B8
spring.datasource.username=postgres
spring.datasource.password=4524267911Ljq...

server.port=8080